repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [json]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.1
    hooks:
      - id: check-jsonschema
        files: ^metadata/.*\.json$
        args: ["--schemafile", "metadata-schema.json"]
