repos:
  - repo: local
    hooks:
      - id: jsonschema2md
        name: Convert JSON schema to markdown
        description: This hook converts a JSON schema to markdown.
        entry: jsonschema2md
        language: node
        types: [json]
        args: ["-d", schemas, "-o", markdown, -e, json]
        files: .*
        additional_dependencies:
          - "@adobe/jsonschema2md@v8"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [json]
